name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
      - 'K8s/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.5
    
    - name: Build
      run: go build -o go-web-app

    - name: Test
      run: go test ./...
  
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses:  actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        token: ${{ secrets.TOKEN }}
    
    - name: Update tag in the Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml
    
    - name: Commit and push changes
      run: |
        git config --global user.email "mandali.harish@gmail.com"
        git config --global user.name "Mandali Harish Kumar"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push
